prelude:
- wget https://github.com/gentoo/gentoo/archive/c0c5c5d7c44589ed5541acaf90917457baec804a.tar.gz -O /tmp/tree.tar.gz
steps:
- mkdir -p /var/db/repos /var/cache/binpkgs /var/cache/distfiles
- tar xvf /tmp/tree.tar.gz -C  /var/db/repos
- mv /var/db/repos/* /var/db/repos/gentoo
requires:
- category: "layer"
  name: "base"
  version: ">=0.1"
