language: go
sudo: true
services:
  - docker
go:
  - "1.12"
env:
  - "GO15VENDOREXPERIMENT=1"
before_install:
  - go get github.com/mudler/luet
  - mv $GOPATH/bin/luet ./luet
  - sudo cp -rfv luet /usr/bin/luet
  - curl -LO https://storage.googleapis.com/container-diff/latest/container-diff-linux-amd64 && chmod +x container-diff-linux-amd64 && mkdir -p $HOME/bin && sudo mv container-diff-linux-amd64 /usr/bin/container-diff
script:
  - sudo luet build --all
