steps:
- layman -S
- cd /var/lib/layman/sabayon && git reset --hard a29d55fce00145b46015f91fc384f8666485b0a7
- cd /var/lib/layman/sabayon-distro && git reset --hard 8a833b3cfef14a32988f530e6b871df248ce82e6
requires:
- category: "layer"
  name: "core-desktop-build"
  version: ">=0.1"
