prelude:
- wget https://github.com/gentoo/gentoo/archive/b91ba099ce82f8e126342da6e616a3e1c822cfa4.tar.gz -O /tmp/tree.tar.gz
steps:
- mkdir -p /var/db/repos /var/cache/binpkgs /var/cache/distfiles
- tar xvf /tmp/tree.tar.gz -C  /var/db/repos
- mv /var/db/repos/* /var/db/repos/gentoo
- cp -rfv /var/db/repos/gentoo/profiles/ /usr/portage/
- mkdir -p /usr/portage/distfiles/ && wget http://www.gentoo.org/dtd/metadata.dtd -O /usr/portage/distfiles/metadata.dtd
- chown -R root:portage /usr/portage/distfiles/
- chmod g+w /usr/portage/distfiles/
- touch /usr/portage/.keep
requires:
- category: "layer"
  version:  ">=0.20191208"
  name:     "base"
