prelude:
- source /etc/profile
# Temporary workaround for delay on DHCP response
- sleep 4
- eselect python set python3.6
- enman add https://dispatcher.sabayon.org/sbi/namespace/devel/devel
- equo up && equo upgrade
- wget https://raw.githubusercontent.com/Sabayon/sabayon-sark/develop/sark-functions.sh -O /sbin/sark-functions.sh
- chmod 755 /sbin/sark-functions.sh
- cp -rfv /sbin/sark-functions.sh /etc/sark-functions
- chmod 755 /etc/sark-functions
- wget https://raw.githubusercontent.com/Sabayon/devkit/develop/builder -O /usr/sbin/builder
- wget https://raw.githubusercontent.com/Sabayon/sabayon-sark/develop/sark-localbuild -O /usr/bin/sark-localbuild
- wget https://raw.githubusercontent.com/Sabayon/sabayon-sark/develop/sark-localcreaterepo -O /usr/bin/sark-localcreaterepo
- wget https://raw.githubusercontent.com/Sabayon/devkit/develop/dynlink-scanner -O /usr/bin/dynlink-scanner
- wget https://dispatcher.sabayon.org/sbi/namespace/pkgs-checker-cross-bin/pkgs-checker-latest-linux-amd64 -O /usr/bin/pkgs-checker
- chmod a+x /usr/sbin/builder
- chmod a+x /usr/bin/sark-localcreaterepo
- chmod a+x /usr/bin/sark-localbuild
- chmod a+x /usr/bin/pkgs-checker
- chmod a+x /usr/bin/dynlink-scanner
- ACCEPT_LICENSE=* equo i dev-perl/Sort-Versions
steps:
- bash build.sh
includes:
- artifacts
requires:
- category: "community"
  name: "definitions"
  version: ">=0.1"
