unpack: true
requires:
- category: "layer"
  name: "base"
  version: ">=0.1"
includes:
- /bin$|/bin/.*
- /boot$|/boot/.*
- /dev$|/dev/.*
- /etc$
# We need to skip hostname, hosts and resolv.conf
# Explictly listing what we want from etc
- /etc/DIR_COLORS.*
- /etc/X11.*
- /etc/bash.*
- /etc/bindresvport.blacklist.*
- /etc/binfmt.d.*
- /etc/ca-certificates.*
- /etc/ca-certificates.conf.*
- /etc/conf.d.*
- /etc/cron.daily.*
- /etc/csh.env.*
- /etc/dbus-1.*
- /etc/default.*
- /etc/dispatch-conf.conf.*
- /etc/e2fsck.conf.*
- /etc/e2scrub.conf.*
- /etc/env.d.*
- /etc/environment.*
- /etc/etc-update.conf.*
- /etc/filesystems.*
- /etc/fstab.*
- /etc/gai.conf.*
- /etc/gentoo-release.*
- /etc/group.*
- /etc/gshadow.*
- /etc/host.conf
- /etc/init.d.*
- /etc/inputrc.*
- /etc/iproute2.*
- /etc/issue.*
- /etc/issue.logo.*
- /etc/kernel.*
- /etc/ld.so.cache.*
- /etc/ld.so.conf.*
- /etc/ld.so.conf.d.*
- /etc/locale.conf.*
- /etc/locale.gen.*
- /etc/localtime.*
- /etc/login.defs.*
- /etc/logrotate.d.*
- /etc/machine-id.*
- /etc/man_db.conf.*
- /etc/mime.types.*
- /etc/mke2fs.conf.*
- /etc/modprobe.d.*
- /etc/modules-load.d.*
- /etc/mtab.*
- /etc/nanorc.*
- /etc/netconfig.*
- /etc/networks.*
- /etc/nsswitch.conf.*
- /etc/os-release.*
- /etc/pam.d.*
- /etc/passwd.*
- /etc/profile.*
- /etc/profile.d.*
- /etc/profile.env.*
- /etc/protocols.*
- /etc/python-exec.*
- /etc/resolv.conf.*
- /etc/rhashrc.*
- /etc/rmt.*
- /etc/rpc.*
- /etc/rsyncd.conf.*
- /etc/runlevels.*
- /etc/sandbox.conf.*
- /etc/sandbox.d.*
- /etc/security.*
- /etc/services.*
- /etc/sgml.*
- /etc/shadow.*
- /etc/shells.*
- /etc/skel.*
- /etc/ssh.*
- /etc/ssl.*
- /etc/sysctl.conf.*
- /etc/sysctl.d.*
- /etc/systemd.*
- /etc/terminfo.*
- /etc/tmpfiles.d.*
- /etc/udev.*
- /etc/udhcpd.conf.*
- /etc/wgetrc.*
- /etc/xattr.conf.*
- /etc/xdg.*
- /etc/xinetd.d
- /etc/xml.*

- /home$|/home/.*
- /lib$|/lib.*
- /media$|/media/.*
- /mnt$|/mnt/.*
- /opt$|/opt/.*
- /root$|/root/.*
- /run$|/run/.*
- /sbin$|/sbin/.*
- /usr$|/usr/.*
- /var$|/var/.*
