prelude:
- wget https://github.com/gentoo/gentoo/archive/c0c5c5d7c44589ed5541acaf90917457baec804a.tar.gz -O /tmp/tree.tar.gz
steps:
- mkdir -p /var/db/repos /var/cache/binpkgs /var/cache/distfiles
- tar xvf /tmp/tree.tar.gz -C  /var/db/repos
- mv /var/db/repos/* /var/db/repos/gentoo
- mkdir -p /usr/portage/distfiles/ && wget http://www.gentoo.org/dtd/metadata.dtd -O /usr/portage/distfiles/metadata.dtd
- chown -R root:portage /usr/portage/distfiles/
- chmod g+w /usr/portage/distfiles/
- touch /usr/portage/.keep
requires:
- category: "layer"
  name: "base"
  version: ">=0.1"
