prelude:
- equo up
- equo i dev-lang/go
- git clone https://github.com/mudler/luet
steps:
- cd luet && make build && mv luet /luet
includes:
- ^\/luet
requires:
- category: "layer"
  name: "build"
  version: ">=0.1"
